### ISSUE TITLE
Intended usage of resulting `index.html`?

### ISSUE THREAD

**Issue by A-Baji** [wilhelmer/mkdocs-multirepo#4]
I'm confused on how to use the resulting `index.html` in [my root doc repo](https://github.com/A-Baji/mk-docs-main) after running `mkdocs-multirepo --build`.

The [method I'm using](https://raw.githubusercontent.com/A-Baji/mk-docs-main/master/docs/index.md) looks fine, but it feels "hacky" and the top level search does not work. Is there a way to display the repositories similar to the way I am in [my demo](https://a-baji.github.io/mk-docs-main/) (as opposed to listing them in the left-hand navigation menu like in the docs' demo), but also include a top level search?

**Comment by wilhelmer** [comment]
My idea was not to use MkDocs for the main page at all, but rather create a standard HTML page, as shown in the [example](https://github.com/wilhelmer/mkdocs-multirepo#indextpl). No markdown, just plain HTML.

Then, you can implement search using a third-party service like [DocSearch](https://docsearch.algolia.com) that crawls over the published subprojects and generates a search index which you can integrate on your main page. This also has nothing to do with MkDocs, it's a generic search service for any website.
