### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by jorgegomezcq** [wilhelmer/mkdocs-multirepo#5]
Hi,

Is this project still active?

**Comment by wilhelmer** [comment]
I created this project for prototyping when we were looking for a solution for our large documentation project. In the end, we decided to use [mkdocs-monorepo](https://github.com/backstage/mkdocs-monorepo-plugin) instead.

So no, this project is no longer active, as long as no one else wants to maintain it.

The good news is that @squidfunk is currently developing an alternative called [projects](https://squidfunk.github.io/mkdocs-material/setup/building-an-optimized-site/#built-in-projects-plugin), which already is much better than this. It's part of MkDocs Material Insiders, so you currently have to pay for it, but you should do so anyway 😉
